### ISSUE TITLE
feat: Criar uma extensão de inicialização de projetos

### ISSUE THREAD

**Issue by roooque** [discloud/bash#1]
Transformar o [`discloud/bash`]() em uma ferramenta de gerenciamento de projetos, com comandos como `discloud new` ou `discloud commit`. 

Ao invés de utilizar `bash` como a linguagem de script, seria conveniente utilizar linguagens como Python ou JavaScript (Node.js) para isso, já que as duas linguagens possuem suporte para sistemas operacionais POSIX e Windows.

**Comment by pedroricardo** [comment]
O projeto de inicialização da CLI já esta em construção a algum tempo, e vamos sim transformar a discloud/bash em uma cli.
Lancei primariamente esse script para irmos testando a nossa API que será o coração da CLI
