### ISSUE TITLE
English readme

### ISSUE THREAD

**Issue by AnotherCodingUser** [discloud/bash#2]
Adding a English readme file would be appreciated, I find it hard to use the current one

**Comment by DiogoMarques2003** [comment]
@EquablePJ Can you check if everything is ok with the English translation?

**Comment by AnotherCodingUser** [comment]
@DiogoMarques2003 Where is the English translation?

**Comment by DiogoMarques2003** [comment]
@EquablePJ https://github.com/discloud/bash/pull/3/commits/912b83b2254ad54b31681a675302e52c0b7942d7

**Comment by AnotherCodingUser** [comment]
Everything looks fine thank you so much!
